# Site settings
title: Sydney Freediving Festival
description: "Join us for the Sydney Freediving Festival on February 24-25, 2024."
baseurl: "/SydneyFreedivingFestival" # the subpath of your site, e.g. /blog
url: "https://emiliatjernstrom.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed here will not be processed by Jekyll.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Optional: include for GitHub Pages
# github: [metadata]
